<?
$PERM["lk-prodavtsa"]["2"]="D";
$PERM["lk-prodavtsa"]["3"]="D";
$PERM["lk-prodavtsa"]["4"]="D";
$PERM["lk-prodavtsa"]["8"]="D";
$PERM["lk-prodavtsa"]["6"]="D";
$PERM["lk-prodavtsa"]["7"]="X";
$PERM["lk-prodavtsa"]["5"]="D";
$PERM["lk-pokupatelya"]["2"]="D";
$PERM["lk-pokupatelya"]["3"]="D";
$PERM["lk-pokupatelya"]["4"]="D";
$PERM["lk-pokupatelya"]["8"]="D";
$PERM["lk-pokupatelya"]["6"]="X";
$PERM["lk-pokupatelya"]["7"]="D";
$PERM["lk-pokupatelya"]["5"]="D";
$PERM["bitrix"]["8"]="D";
$PERM["search"]["5"]="W";
$PERM["products"]["5"]="W";
$PERM["services"]["5"]="W";
$PERM["news"]["5"]="W";
$PERM["contacts"]["5"]="W";
$PERM["company"]["5"]="W";
$PERM["index.php"]["5"]="W";
$PERM["/"]["*"]="R";
?>